### ISSUE TITLE
Item thumbnail: image size not reported correctly

### ISSUE THREAD

**Issue by jimherries** [ChrisMahlke/contribute-dev#156] opened 2015-05-12 20:49 UTC
On item thumbnail upload, if it is not the required size the reported image pixel dimensions is always different than the actual pixel dimensions of the image.

To reproduce, attempt to upload any image that is not 200x133. Find a file, check its dimensions manually, and then try to upload it.

**Comment by jimherries** [comment] 2015-06-09 16:45
On DEVEXT today, Image pixel dimensions are still not reported correct.
![screenshot 2015-06-03 11 50 21](https://cloud.githubusercontent.com/assets/5177430/8063896/27e6b81c-0e8c-11e5-86e9-cacde505a003.png)

Also, there is a typo in the message box after you choose an image: dimesnions

**Comment by ChrisMahlke** [comment] 2015-06-09 18:00
@jimherries I just tried these sizes and the <b>correct</b> size was reported back:
150 x 150
133 x 200
200 x 133
201 x 133
800 x 450
1000 x 1000
2560 x 1600
4256 x 2394

Can you send me the image in the screen shot above so I can take a look?  Otherwise, I'm unable to reproduce and will need to close the issue.

**Closed** 2015-06-11 22:34 UTC
Labels: bug
